services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: lg-db-pd
      MYSQL_DATABASE: lazygrocer
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: lg-db-pd
      MYSQL_DATABASE: lazygrocer
    ports:
      - "3306:3306"
    volumes:
      - lg-db-volume:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  lg-db-volume:
    driver: local