@startuml LazyGrocerActivityDiagram

skinparam activity {
    BorderColor DarkSlateGray
    BackgroundColor LightBlue
    FontSize 14
}

header Activity Diagram
title LazyGrocer Database Design
footer CS3200 Final Project: Michael Montanaro 2024

start
:User interacts with LazyGrocer;
if (using UI) then (yes)
    :App opens on device;
    if (logged in) then (yes)
        :App shows user profile;
    else (no)
        :Show local user list;
        if (user selected) then (yes)
        :App shows user profile;
        else (no)
            stop
        endif
    endif
else (no)
  :User interacts with CLI tools;
  :User selects any of the following options:;
  :write;
  :url;
  :recipe;
  :instruction;
  stop
endif
if (User selects "Recipes") then (yes)
        :App displays all recipes;
        if (User selects "Add Recipe") then (yes)
            :App allows user to add recipe;
            :App shows recipe view;
        else (no)
            :loop back to display all recipes;
            if (User opens a recipe) then (yes)
                :App shows recipe view;
                :User can review recipe
                :User can edit recipe;
                :User can delete recipe;
            else (no)
                if (User selects a recipe) then (yes)
                    if (User selects "Create Ingredient List") then (yes)
                        :App creates ingredient list;
                        :App displays ingredient list;
                        if (User names ingredient list) then (yes)
                            :App updates list name;
                        else (no)
                            :App auto-names list;
                        endif
                    else (no)
                        stop
                    endif
                else (no)
                    stop
                endif
            endif
        endif
else (no)
    if (User selects "Ingredients") then (yes)
        :App displays all ingredients;
        if (User selects "Merge Ingredients") then (yes)
            :App allows user to combine duplicate ingredients;
            :App updates ingredient list view;
        else (no)
            :loop back to display all ingredients;
            stop
        endif
        if (User opens an ingredient) then (yes)
            :App shows ingredient view;
            :User can edit inventory amount;
            :User can rename the ingredient;
        else (no)
            if (User selects an ingredient) then (yes)
                if (User selects "Create Recipe List") then (yes)
                    :App creates recipe list;
                    :App displays recipe list;
                    if (User names recipe list) then (yes)
                        :App updates list name;
                    else (no)
                        :App auto-names list;
                    endif
                else (no)
                    stop
                endif
            else (no)
                stop
            endif
        endif
    else (no)
        if (User selects "Recipe Lists") then (yes)
            :App shows saved recipe lists;
            if (User opens a recipe) then (yes)
                :App shows recipe view;
                :User can review recipe
                :User can edit recipe;
                :User can delete recipe;
            else (no)
                :User can check off recipes;
                :User can rename list;
            endif
        else (no)
            if (User Selects "Ingredients List") then (yes)
                :App shows saved ingredient lists;
                if (User opens list) then (yes)
                    if (User opens an ingredient) then (yes)
                        :App shows ingredient view;
                        :User can edit inventory amount;
                        :User can rename the ingredient;
                    else (no)
                        :User can rename list;
                        :User can check off ingredients;
                        :User can add or remove ingredients;
                        :User prompted for quantity added;
                    endif
                else (no)
                    :User can return to user profile;
                    stop 
                endif
            else (no)
                :App stays on user profile;
                stop
            endif
        endif
    endif
endif
if (User saves) then (yes)
    :App uploads changes to database;
    stop
else (no)
    :App does not save changes to database;
    stop
endif
@enduml