@startuml LazyGrozerERDdiagram

header ERD Diagram
title LazyGrocer Database Design
footer CS3200 Final Project: Michael Montanaro 2024

entity Recipe {
    title <<PK>> 
    description
    rating
    meal_timing
    favorite?
    date_published
}

entity RecipeList {
    name <<PK>>
    description
}

entity Instruction {
    cook_time
    servings
    calories
    steps
    url
}

entity Ingredient {
    name <<PK>>
    inventory
    last_added
}

entity IngredientList {
    name <<PK>>
    description
}

entity Chef {
    username <<pk>>
    first_name
    last_name
    email
}

object includes {
    quantity
}
diamond DIncludes

Recipe }|-- DIncludes
DIncludes --|{ Ingredient: >
DIncludes . includes
Recipe }|-o{ RecipeList: includes <
Ingredient }|-o{ IngredientList: for <
Chef ||--o{ Recipe: publishes >
Instruction ||-|| Recipe: explains >

@enduml