@startuml LazyGrozerERDdiagram

header ERD Diagram
title LazyGrocer Database Design
footer CS3200 Final Project: Michael Montanaro 2024

object Recipe {
    title <<PK>> 
    description
    date_published
}

object Rating {
    score 
    description
    date_added
}

object Favorite {
    date_added
    description
}

object RecipeList {
    name <<PK>>
    description
}

object Instruction {
    cook_time
    prep_time
    servings
    calories
}

object Step {
    id <<PK>>
    description
}

object Ingredient {
    name <<PK>>
    inventory
    last_added
}

object GroceryList {
    name <<PK>>
    description
}

object includes {
    quantity
}
diamond DIncludes
diamond stepdiamond

Rating }o--o| Recipe 
Favorite }o--|| Recipe 
Recipe }|-- DIncludes
DIncludes --|{ Ingredient: >
DIncludes . includes
Recipe }|-o{ RecipeList: contains <
Ingredient }|-o{ GroceryList: for <
Instruction ||- stepdiamond
stepdiamond -|| Recipe: explains >
stepdiamond --|{ Step: describes <

@enduml